import { Inter } from "next/font/google";
import "./globals.css";
import CryptoContextProvider from "@/store/crypto-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cryptocurrencies Historical Prices",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black/90 ${inter.className}`}>
        <main>
          <CryptoContextProvider>{children}</CryptoContextProvider>
        </main>
      </body>
    </html>
  );
}
