import { Inter } from "next/font/google";
import "./globals.css";
import CryptoContextProvider from "@/store/crypto-context";
import Header from "@/components/header/header";
import ScrollToTop from "@/components/UI/scroll-to-top";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cryptocurrency Historical Price Dashboard App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black/90 ${inter.className}`}>
        <Header />
        <CryptoContextProvider>{children}</CryptoContextProvider>
        <ScrollToTop />
      </body>
    </html>
  );
}
